
# _____  _____   _____ _____             _   _     
#|  __ \|  __ \ / ____|  __ \           | | | |    
#| |__) | |__) | |  __| |  | | ___  __ _| |_| |__  
#|  _  /|  ___/| | |_ | |  | |/ _ \/ _` | __| '_ \ 
#| | \ \| |    | |__| | |__| |  __/ (_| | |_| | | |
#|_|  \_\_|     \_____|_____/ \___|\__,_|\__|_| |_|
#

#Time in seconds until the corpse despawns. Set to -1 for the copse to never despawn.
corpse-time: 120

#Spawn a corpse when the player dies?
on-death: true

#Put the players items into a GUI when they die? Click the the corpse to open the GUI.
looting-inventory: true

#Should the corpse automaticly despawn after it has been looted? (Only has effect is looting-inventory is true!)
despawn-after-looted: true

#Show the username of the player? If you set this to false ' ' will be used for the username.
#The skin will still show even if you choose not do display the username.
show-tags: true

#This is used to specify what world(s) corpses should spawn when somebody dies.
#Set world to 'all' for every world.
#Use '|' to add multiple worlds.
world: all

#Title of inventory created when you click the corpses head to loot it. 
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
#Minecraft has a 32 character limit on GUI lengths. If your title is more then that you will get a error on the console.
gui-title: "%corpse%'s Items"

#This is the username of the corpse.
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
#Minecraft has a 16 character limit on name lengths. If your title is more then that you will get a error on the console.
username-format: "%corpse%"

#This is the message sent when you finish looting the corpse. Set the message to "none" to disable.
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
finish-looting-message: "&7You have finished looting %corpse%'s corpse."

#Due to a Minecraft quirk with how the corpses work, the hitboxes were not normal player hitboxes.
#I have now made it so a invisible Cows spawn that covers the whole corpse.
#When you click on the invisible Cow it does the same thing as clicking on the corpse.
#Set to false to use the old glitchy hitboxes.
new-hitboxes: true

#Should we render player armor and items on the corpses?
#Set to false to not render player armor and items on the corpses
render-armor: true

#Should we save corpses on restart?
#Note: v1_8_R1 and below will not save. (1.8.8+ will save)
save-corpses: true

#Can players revive another player?
revive: true

#Set the max player distance for revive.
revive-distance: 5

#Title of inventory created when you click for revive. 
#%player% gets replaced with the player name.
#Color codes and unicode characters work, but might be glitchy.
#Minecraft has a 32 character limit on GUI lengths. If your title is more then that you will get a error on the console.
gui-revive-title: "&7Revive &c%player%"

#First item material in the gui (Default: RED_WOOL). 
gui-revive-material-red: "RED_WOOL"

#Second item material in the gui (Default: GREEN_WOOL). 
gui-revive-material-green: "GREEN_WOOL"

#Can players skip spectator mode?
skip-spec: false

#Text of the action bar message when player are in Death Spectating. 
#Color codes and unicode characters work, but might be glitchy.
action-bar-skip-text: "&7Press &cShift &7to reincarnate directly."

#Time in seconds until the player can respawn.
spectator-time: 45

#Chat message when player are in Death Spectating. 
#%seconds% gets replaced with the spectator time.
#Color codes and unicode characters work, but might be glitchy.
chat-message-spectating: "&7You are dead! Reappear in &c%seconds% &7seconds."

#title message when player are in Death Spectating. 
#%seconds% gets replaced with the remaining seconds.
#Color codes and unicode characters work, but might be glitchy.
title-text: "&cYou are dead!."

#subtitle message when player are in Death Spectating. 
#%seconds% gets replaced with the remaining seconds.
#Color codes and unicode characters work, but might be glitchy.
subtitle-text: "&7Reappearance in &c%seconds% &7seconds!"

#title message when player are in revive. 
#Color codes and unicode characters work, but might be glitchy.
revive-title-text: ""

#subtitle message when player are in revive. 
#Color codes and unicode characters work, but might be glitchy.
revive-subtitle-text: "&7Revive in progress!"

#Use rpg spawn?
rpg-spawn: true

#Broadcasty message when player Die. 
#%DeathMessage% gets replaced with the minecraft death message.
#%killer% gets replaced with the killer player name.
#%killed% gets replaced with the killed player name.
#%death_symbol% gets replaced with the death symbol.
#Color codes and unicode characters work, but might be glitchy.
custom-death-message: "&7(&c%death_symbol%&7) %DeathMessage%"

#Use HolographicDisplays?
holo: true

#HolographicDisplays text. 
#%seconds% gets replaced with the remaining seconds.
#Color codes and unicode characters work, but might be glitchy.
holo-text: "&cShift + Click &7for &6Revive! &7(&c %seconds% &7)"

#HolographicDisplays text. 
#%seconds% gets replaced with the remaining seconds.
#Color codes and unicode characters work, but might be glitchy.
holo-revive-text: "&7Revive in progress! &7(&c %seconds% &7)"

#Use class revive?
class-revive: false

#Class Name. 
#revive-class-name: medic > for only one class.
#revive-class-name: medic,druid,... > for several classes.
revive-class-name: "medic"

#Use multiply  Time? 
use-multiply-time: false

#Multiply  Time. 
#In seconds.
multiply-time: 2

#Time after playerDeath for reset Multiply Spec Time. 
#In seconds.
reset-multiply-time: 20

#Op can Bypass respawn time?. 
op-bypass: true

#If RPGSpawn disable. 
#Respawn at player body?
respawn-at-body: false

#Prevent movement in spectator mode? 
prevent-movement: false
